config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'

  # get 'contact', to: 'publics#contact', as: 'contact'

  resources :products do
    collection do
      get :auction
      get :featureds, to: 'products#featured'
      get 'wishlist/:id', to: 'products#wishlist', as: 'wishlist'
      post :checkout_bid
    end
    member do
      match :upvote, path: 'like', via: [:get, :post, :put]
      get 'reviews', to: 'products#reviews'
      delete 'reviews/:rate_id', to: 'products#delete_reviews', as: 'delete_rate'
      post 'reviews', to: 'reviews#create'
    end
  end
  resources :favorites do
    collection do
      get :wishlist
    end
  end
  resources :subscribes
  resources :landing_pages
  resources :comments
  resources :reports, only: [:create]
  resources :inquiries do
    collection do
      post :create_instant_message
    end
  end
  resources :guest_books
  resources :users do
    member do
      match :upvote, path: 'like', via: [:get, :post, :put]
    end
  end
  resources :blogs do
    member do
      get :category
    end
    collection do 
      get :results
    end
  end
  resources :xhrs do
    collection do
      get :cities
      get :districts
      get :villages
      get :sub_categories
      get :brands
    end
  end

  namespace :backend do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :merchants do
      collection do
        post :do_multiple_act
      end
    end
    resources :categories do
      collection do
        post :do_multiple_act
      end
    end
    resources :products do
      collection do
        get :pending
        get :archive
        post :do_multiple_act
      end
      member do
        get :restore
      end
    end
    resources :regions do
      collection do
        post :do_multiple_act
      end
    end
    resources :reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :comments do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_pages do
      collection do
        post :do_multiple_act
      end
    end
    resources :subscribes do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :category_blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :web_settings
  end

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members, only: [:edit, :update, :show]
    resources :merchants, only: [:edit, :update, :show]
    resources :products do
      collection do
        get :pending
        get :archive
      end
      member do
        get :restore
      end
    end
    resources :favorites
    resources :inquiries
  end
end

app/views/shareds/_already_order.html.slim
button class="btn btn-info btn-lg full-width no-radius"
  | You have already order this item

app/views/shareds/_carousel.html.slim
section.section-carousel
  #transition-timer-carousel class="home-carousel carousel slide transition-timer-carousel" data-ride="carousel"
    .carousel-inner
      - @setting.galleries.each_with_index do |resource, index|
        div class=['item', "#{'active' if index == 0}"]
          = image_tag resource.file
    a class="left carousel-control" href="#transition-timer-carousel" data-slide="prev"
      span.glyphicon.glyphicon-chevron-left
    a class="right carousel-control" href="#transition-timer-carousel" data-slide="next"
      span.glyphicon.glyphicon-chevron-right

    hr class="transition-timer-carousel-progress-bar animate"

    .main-text
      .text-center
        h1 Cari Barang Yang Anda Inginkan Disini
        p Anda yang menentukan barang yang dipilih cocok untuk anda!
        br
        = link_to products_path do
          button class="btn btn-alert btn-new"
            | Barang Baru
        button class="btn btn-or" ATAU
        = link_to products_path do
          button class="btn btn-alert btn-second"
            | Barang Bekas
        br
        = link_to '<i class="fa fa-plus-square-o"></i> Pasang Iklan'.html_safe, new_product_path, class: 'btn btn-lg btn-success'

app/views/shareds/_cart_text.html.slim
= link_to "<span class='fa fa-shopping-cart'></span>&nbsp;<span>#{current_order.order_items.size}</span>".html_safe, orders_path

app/views/shareds/_chat.html.slim
- user = @product.try(:user) || @user
- profile = user.try(:profile)
.panel.panel-default.chat-window
  .panel-heading
    h3 class="panel-title"
      = @user.try(:merchant_info).try(:title)
      span class="glyphicon glyphicon-remove"
      span class="glyphicon glyphicon-minus"
  .panel-body
    .break
    .row
      .col-xs-4
        = link_to image_tag(profile.avatar.url(:small)), user_path(user), class: "pull-left ava-list"
      .col-xs-8
        b
          = user.try(:username)
        .useridUser Id: #{user.try(:code)}
      .col-xs-12
        .wellcome
          p 'Hi, saya lihat bahwa anda sedang melihat listing saya, ada yang bisa saya bantu?'
      .col-xs-12
        .wellcome
          p class="last-name"
          p class="last-message"
  .panel-form
    = form_for Inquiry.new, url: create_instant_message_inquiries_path, method: 'post', html: {class: 'form-sms-instant-message'} do |f|
      - if @product.present?
        = f.hidden_field :inquiriable_id, value: @product.id
        = f.hidden_field :inquiriable_type, value: @product.class
        = f.hidden_field :owner_id, value: @product.try(:user).try(:id)
      - else
        = f.hidden_field :owner_id, value: @user.try(:id)
      - unless current_user.present?
        / = f.text_field :name, class: 'form-name', required: true, placeholder: 'name ...'
        / = f.text_field :phone, class: 'form-phone', required: true, placeholder: 'phone ...'
        = f.email_field :email, class: 'form-email', required: true, placeholder: 'email ...'
      - else
        = f.hidden_field :name, class: 'form-name', value: current_user.username
      = f.text_field :message, class: "form-chat", placeholder: 'messages ...', required: true
      button class="btn btn-chat" type="submitSend" Send

app/views/shareds/_footer.html.slim
footer.col-xs-12.footer
  .container
    .row
      .col-md-12
        ul.footer-box-list
          - @landing_pages.each do |page|
            li
              = link_to page.title, landing_page_path(page)
section.copyright
  .container
    .row
      .col-xs-12
        center
          p #{@setting.footer_tags}

= render 'shareds/sign_in'

app/views/shareds/_form_contact.html.slim
.modal.fade.modal-contact id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true"
  .modal-dialog.modal-sm
    .modal-content.modal-content-message
      .modal-header.modal-header-info
        h3 align="center" Box Message
      .modal-body.modal-sign.modal-contact-form
        = form_for Inquiry.new, url: inquiries_path, method: 'post' do |f|
          - if @product.present?
            = f.hidden_field :inquiriable_id, value: @product.id
            = f.hidden_field :inquiriable_type, value: @product.class
            = f.hidden_field :owner_id, value: @product.try(:user).try(:id)
          - else
            = f.hidden_field :owner_id, value: @user.try(:id)
          fieldset
            - unless current_user.present?
              div
                .form-group
                  label class="control-label" Name:
                  .controls
                    = f.text_field :name, class: "form-control", required: true, placeholder: 'ex. alam topani ...'
                .form-group
                  label class="control-label" Phone:
                  .controls
                    = f.text_field :phone, class: "form-control", required: true, placeholder: 'ex. +6285.2345 ...'
                .form-group
                  label class="control-label" Email:
                  .controls
                    = f.email_field :email, class: "form-control", required: true, placeholder: 'ex. alam@example.com ...'
            .form-group
              label class="control-label" Message:
              .controls
                = f.text_area :message, class: "form-control", required: true 
            .form-group
              .controls
                = f.submit 'Send Now', class: "btn btn-primary btn-block btn-success"

app/views/shareds/_gmap_js.html.erb
<script type="text/javascript">
  $('#maps').gmap3({
    map:{
      options:{
        center:[<%= @setting.longitude %>, <%= @setting.latitude %>],
        zoom: 15,
        scrollwheel: false
      }
    },
    marker:{
      values:[
      {latLng:[<%= @setting.longitude %>, <%= @setting.latitude %>], data:"<b><%= @setting.title %></b><br><%= @setting.address %>"},
      ],
      options:{
        draggable: false
      },
      events:{
        mouseover: function(marker, event, context){
          var map = $(this).gmap3("get"),
          infowindow = $(this).gmap3({get:{name:"infowindow"}});
          if (infowindow){
            infowindow.open(map, marker);
            infowindow.setContent(context.data);
          } else {
            $(this).gmap3({
              infowindow:{
                anchor:marker,
                options:{content: context.data}
              }
            });
          }
        },
        mouseout: function(){
          var infowindow = $(this).gmap3({get:{name:"infowindow"}});
          if (infowindow){
            infowindow.close();
          }
        }
      }
    }
  });
</script>

app/views/shareds/_invoice.html.slim
.panel.panel-default
  .panel-heading
    h4.text-center.uppercase
      | Invoice <strong>#{@order.code}</strong>
    center.small
      | <b>Invoice Date : </b> 
      = @order.try(:purchased_at).strftime("%B, %d, %Y") if @order.purchased_at
      br
      | <b>Due Date : </b> 
      = (@order.try(:purchased_at)+ 3.days).strftime("%B, %d, %Y") if @order.purchased_at
      - if current_user.admin?
        = form_for @order, url: backend_order_path(@order), method: 'put', html: {class: ''} do |f|
          = f.select :order_status_id, options_for_select(PaymentStatus.to_a, @order.order_status_id), {prompt: 'Select Status'}
          = f.submit :change, class: 'btn btn-xs btn-info'
  .panel-body
    .row
      .col-md-12
        h5.uppercase
          | Invoiced To
        = @order.try(:payer_company)
        br
        = @order.try(:payer_name)
        br
        small
          | Shipping: &nbsp;
          = @order.try(:payer_address) 
    .break
    .shopping-cart
      - @stakeholders.each do |stakeholder|
        .row
          .col-md-12
            .catalog-item-show
              .table-responsive.table-order-list
                table class="table table-striped"
                  thead
                    tr
                      td width="35%"
                        | <strong>Order From Store <a href="#{user_path(stakeholder.user)}">#{stakeholder.user.merchant_info.title.titleize}</a></strong>
                      td class="text-center"
                        | <strong>Quantity</strong>
                      td class="text-center"
                        | <strong>Weight</strong>
                      td class="text-center"
                        | <strong>Size</strong>
                      td width="14%" class="text-right"
                        | <strong>Item Price</strong>
                  tbody
                    - stakeholder.order_items.each do |order_item| 
                      tr
                        td
                          .avatar-author
                            = image_tag order_item.try(:product).try(:galleries).try(:first).try(:file).url(:medium)
                          small.uppercase
                            | Id #{@order.code} <br>
                          = link_to "#{order_item.product.title}", product_path(order_item.product.slug), class: 'title-product'
                        td.text-center
                          span
                            = order_item.quantity
                        td.text-center
                          | #{order_item.weight.to_i} Gram
                        td.text-center
                          span
                            = order_item.o_size
                            = 'All Size' if order_item.o_size.blank?
                        td.text-right
                          span
                            = get_currency(order_item.total_price)
                    tr
                      td class="highrow"
                      td class="highrow"
                      td class="highrow"
                      td class="highrow text-center"
                        | <h5>Total Price Shopping</h5>
                      td class="highrow text-right"
                        | <h5>#{get_currency(stakeholder.price_order)}</h5>
                    tr
                      td class="highrow"
                      td class="highrow"
                      td class="highrow"
                      td class="highrow text-center"
                        | <h5>Shipping #{@order.shipping_method.upcase}</h5>
                        | <small><b>From:</b> #{stakeholder.get_owner_origin_city} - <b>To:</b> #{@order.try(:payer_address)}</small>
                        - if current_user.admin?
                          = form_for stakeholder, url: change_status_shipping_backend_order_path(stakeholder), method: 'put', html: {class: ''} do |f|
                            = f.select :track_order, options_for_select(TrackOrder.to_a, stakeholder.track_order), {prompt: 'Status Track Order'}
                            = f.submit :change, class: 'btn btn-xs btn-info'
                      td class="highrow text-right"
                        | <h5>#{get_currency(stakeholder.total_shipping_price) if stakeholder.total_shipping_price.present?}</h5>
                    tr
                      td class="highrow"
                      td class="highrow"
                      td class="highrow"
                      td class="highrow text-center"
                        | <h5>TOTAL</h5>
                      td class="highrow text-right"
                        | <h5>#{get_currency(stakeholder.total_price)}</h5>

      h4 Transaction
      .table-responsive.table-order-list
        table class="table table-striped"
          thead
            tr
              td class="text-center" width="20%"
                | <strong>Transaction Date</strong>
              td class="text-center" width="20%"
                | <strong>Payer</strong>
              td class="text-center"
                | <strong>Payment To</strong>
              td class="text-center"
                | <strong>Payment Status</strong>
              - unless params[:controller] == 'userpage/order_items'
                td width="14%" class="text-center"
                  | <strong>Total Payment</strong>
          tbody
            tr
              td.text-center
                span
                  = @order.try(:purchased_at).strftime("%B, %d, %Y") if @order.purchased_at
              td.text-center
                span
                  = @order.try(:payer_name)
              td.text-center
                span
                  = @order.try(:paymentTo)
              td.text-center
                span
                  = @order.status?
              - unless params[:controller] == 'userpage/order_items'
                td.text-center
                  span
                    b
                      = get_currency(@order.total_payment?)

      h4 Shipping
      .table-responsive.table-order-list
        table class="table table-striped"
          thead
            tr
              td class="text-center" width="15%"
                | <strong>Receiver</strong>
              td class="text-center" width="25%"
                | <strong>Shipping Method</strong>
              td class="text-center" width="10%"
                | <strong>Phone</strong>
              td class="text-center"
                | <strong>Shipping Address</strong>
          tbody
            tr
              td.text-center
                span
                  = @order.try(:payer_name)
              td.text-center
                span
                  = @order.try(:shipping_method).upcase
                  br
                  - if @order.jne?
                    | Layanan Reguler (RE)
                  - elsif @order.pos?
                    | Surat Kilat Khusus
              td.text-center
                span
                  = @order.try(:payer_phone)
              td.text-center
                span
                  = @order.try(:payer_address)

app/views/shareds/_list_message.html.slim
li
  .header-inbox-pop
    small.pull-left
      | Pesan Masuk (#{@latest_inquiries.size})
    = link_to '<small class="pull-right">Lihat Semua Pesan</small>'.html_safe, userpage_inquiries_path
  .box-inbox-pop
    = '<span class="p-message">Pesan tidak ditemukan!</span>'.html_safe unless @latest_inquiries.present?
    - @latest_inquiries.limit(5).each do |i|
      - if i.parent.present?
        = link_to userpage_inquiry_path(i.parent.id) do
          .list-message-limit
            | <div class='usr'><b>#{i.user.username}</b></div>
            | <div>#{i.message}</div>
      - elsif i.parent.blank?
        = link_to userpage_inquiry_path(i) do
          .list-message-limit
            | <div class='usr'><b>#{i.name || i.email}</b></div>
            | <div>#{i.message}</div>

app/views/shareds/_modal_report.html.slim
.modal.modal-report.fade#modal-report tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true"
  .modal-dialog
    .modal-content
      .box-modal-report
        .report-header
          | Subyek Apa Yang Akan Kamu Laporkan?
        .report-body
          = form_for Report.new, url: reports_path, method: 'post' do |f|
            = f.hidden_field :reportable_id, value: resource.id
            = f.hidden_field :reportable_type, value: resource.class
            .form-group
              h5.pull-left
                | Kategori
              = f.select :category, ReportCategory.to_a, {prompt: 'Pilih Kategori'}, {class: 'form-control'}
            .row
              .col-md-6
                h5.pull-left
                  | Name
                = f.text_field :name, value: "#{current_user.username if current_user.present?}", class: "form-control", placeholder: 'ex. Alam Topani', required: true

              .col-md-6
                h5.pull-left
                  | Email
                = f.email_field :email, class: "form-control", value: "#{current_user.email if current_user.present?}", placeholder: 'ex. mail@example.com', required: true

              .col-md-12
                h5.pull-left
                  | Pesan
                = f.text_area :message, class: "form-control", placeholder: 'Informasi apa yang salah?', required: true

              .col-md-12
                .break
                input.btn.btn-success.btn-modal-submit type="submit" value="Kirim Laporan"

app/views/shareds/_setting.html.slim
= favicon_link_tag "#{@setting.favicon.url(:thumb)}"
meta http-equiv="X-UA-Compatible" content="IE=edge"
meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"

- if params[:controller] == 'products' && params[:action] == 'show'
  - @title = "#{@product.title}"
  - @url = "#{product_url(@product)}"
  title
    = @title
  meta name="author" content="#{@product.user.username rescue nil}"
  meta name='keywords' content="#{@product.title}, #{@product.try(:category).try(:name)}"
  meta name="description" content="#{@product.description}"
  meta property="og:title" content="#{@title}"
  meta property="og:type" content="website"
  meta property="og:site_name" content="#{@url}"
  meta property="og:url" content="#{@url}"
  meta property="og:image" content="#{image_url @product.try(:galleries).try(:oldest).try(:first).try(:file).url(:medium) rescue nil }"
  meta property="og:description" content="#{@title}"
  meta property="article:publisher" content="#{@setting.facebook}"
  meta name="twitter:card" content="summary"
  meta name="twitter:url" content="#{@url}"
  meta name="twitter:title" content="#{@title}"
  meta name="twitter:description" content="#{@title}"
  meta name="twitter:creator" content="#{@product.user.username rescue nil}"
  meta name="twitter:image:src" content="#{image_url @product.try(:galleries).try(:oldest).try(:first).try(:file).url(:medium) rescue nil }"
- else
  title
    = @setting.title
  meta content="#{@setting.author}" name='author'
  meta content="#{@setting.keywords}" name='keywords'
  meta content="#{@setting.description}" name="description"

meta content="#{@setting.robot}" name='robots'
meta content="#{@setting.corpyright}" name='copyright'
meta content="#{@setting.revisit}" name='revisit'
meta content="#{@setting.expires}" name='expires'
meta content="#{@setting.revisit_after}" name='revisit-after'
meta content="#{@setting.geo_placename}" name='geo.placename'
meta content="#{@setting.language}" name='language'
meta content="#{@setting.country}" name='geo.country'
meta content="#{@setting.content_language}" http-equiv='Content-Language'
meta content="#{@setting.distribution}" name='distribution'
meta content="#{@setting.generator}" name='generator'
meta content="#{@setting.rating}" name='rating'
meta content="#{@setting.target}" name='target'
meta content='true' name='MSSmartTagsPreventParsing'
meta content='text/html; charset=UTF-8' http-equiv='Content-Type'
meta content='index, follow' name='googlebot'
meta content='follow, all' name='Googlebot-Image'
meta content='follow, all' name='msnbot'
meta content='follow, all' name='Slurp'
meta content='follow, all' name='ZyBorg'
meta content='follow, all' name='Scooter'
meta content='all' name='spiders'
meta content='all' name='WEBCRAWLERS'
meta content='noodp' name='robots'
meta content='noydir' name='robots'
meta content="#{@setting.robot}" name='search engines'

app/views/shareds/_sign_in.html.slim
.modal.fade.bs-modal-sm id="signin" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true"
  .modal-dialog.modal-sm
    .modal-content
      .modal-header.bg-sky.modal-header-info
        h3 align="center" Masuk
      .modal-body.modal-sign
        = form_for :user, url: user_session_path, method: 'post', html: {class: ""} do |f| 
          fieldset
            .form-group
              = link_to user_omniauth_authorize_path(:facebook), class: 'btn btn-primary-fb' do 
                | <i class="fa fa-facebook pull-left"></i>
                | Masuk Dengan Facebook
            .form-group
              .col-xs-12.or-section
                | <i class="omb-or"></i><span class="omb-span">OR</span>
              .break
            .form-group
              .controls
                = f.text_field :login, class: "form-control", placeholder: "Username or Email" 
            .form-group
              .controls
                = f.password_field :password, class: "form-control password", placeholder: "Password" 
            .row
              .col-md-12
                .form-group
                  = f.check_box :remember_me, class: "grey remember" 
                  | <span>Keep me signed in</span>
              .col-md-12
                .form-group
                  .controls
                    = f.submit 'SignIn',  class: "btn btn-lg btn-primary btn-block"
              .col-md-6
                small
                  | Bukan Member?
                  | <a href="#signup" data-dismiss="modal" data-toggle="modal" data-target=".bs-modal-sm2">Daftar</a>
              .col-md-6
                small
                  = link_to 'Lupa Kata Sandi ?', new_user_password_path

.modal.fade.bs-modal-sm2 id="signup" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true"
  .modal-dialog.modal-sm
    .modal-content
      .modal-header.modal-header-info
        h3 align="center" Daftar
      .modal-body.modal-sign
        = form_for :user, url: user_registration_path, method: 'post', html: {class: "form-horizontal"} do |f| 
          = f.fields_for(:profile_attributes) do |profile| 
            fieldset
              .col-md-12
                .form-group
                  = link_to user_omniauth_authorize_path(:facebook), class: 'btn btn-primary-fb' do 
                    | <i class="fa fa-facebook pull-left"></i> Daftar Dengan Facebook
                .form-group
                  .col-xs-12.or-section
                    | <i class="omb-or"></i><span class="omb-span">OR</span>
                .form-group
                  label class="control-label" for="userid" Nama Lengkap:
                  .controls
                    = profile.text_field :full_name, class: "form-control", required: true 
                .form-group
                  label class="control-label" for="userid" Username:
                  .controls
                    = f.text_field :username, class: "form-control", required: true 
                .form-group
                  label class="control-label" for="Email" Email:
                  .controls
                    = f.email_field :email, class: "form-control", required: true 
                .form-group
                  label class="control-label" for="password" Password:
                  .controls
                    = f.password_field :password, class: "form-control password", required: true 
                .form-group
                  label class="control-label" for="reenterpassword" Password Confirmation:
                  .controls
                    = f.password_field :password_confirmation, class: "form-control password", required: true 
                .form-group
                  label class="control-label" for="confirm"
                  .controls
                    = f.submit 'SignUp', class: "btn btn-lg btn-primary btn-block btn-success"
                .form-group
                  .margin-auto-display-table
                    small 
                      | Sudah Terdaftar?
                      | <a href="#signin" data-dismiss="modal" data-toggle="modal" data-target=".bs-modal-sm">Masuk</a>

app/views/shareds/_top_menu.html.slim
= form_for :search, url: products_path(params), method: 'get', html: {class: 'form-action-search'} do
  div id='top-navigation'
    nav.navbar-default
      .container
        .row
          .col-md-12
            .navbar-header
              button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-megadropdown-tabs"
                span class="sr-only">Toggle navigation
                span class="icon-bar"
                span class="icon-bar"
                span class="icon-bar"
              = link_to "<h1>#{image_tag @setting.logo.url(:small)}</h1>".html_safe, root_path, class: "navbar-brand"
            .collapse.navbar-collapse id="bs-megadropdown-tabs"
              ul.nav.navbar-nav.top-menu
                li class="dropdown mega-dropdown"
                  a href="#" class="dropdown-toggle" data-toggle="dropdown"
                    | Kategori <i class='fa fa-angle-down pull-right'></i> 
                  ul class="dropdown-menu mega-dropdown-menu row"
                    .col-sm-12
                      h3.h-all-categories KATEGORI SEMUA IKLAN
                      hr
                    - @categories.each do |category|
                      li.col-sm-3
                        ul
                          li
                            = link_to "#{image_tag category.file.url(:thumb)} #{category.name}".html_safe, products_path(params.merge(category: category.name))
                    .col-sm-12
                      .all-categories 
                        = link_to 'Lihat Semua Kategori', products_path
                li class="dropdown"
                  = link_to 'Blog', blogs_path
              div class= 'form-top-search navbar-form navbar-left'
                .input-group
                  = text_field_tag :key, nil, class: 'form-control', placeholder: 'Cari Berdasarkan Judul/Nama Toko...'
                  .input-group-btn
                    button class="btn btn-success" type="submit"
                      i class="fa fa-search"
              ul class="nav navbar-nav navbar-right nav-account"
                li
                  = link_to 'Bantuan <i class="fa fa-question-circle"></i>'.html_safe, products_path
                - unless current_user
                  li
                    = link_to 'Daftar', new_user_registration_path
                  li
                    a href="#signin" data-toggle="modal" data-target=".bs-modal-sm"
                      | <i class='fa fa-key'></i> Masuk 
                - else
                  li
                    a.dropdown-toggle.dropdown-toggle-new data-toggle="dropdown"
                      div class="message-btn"
                        span.fa.fa-envelope-o
                        | &nbsp;<span class="count-inbox">#{@latest_inquiries.size}</span>
                    ul.dropdown-menu.dropdown-menu-message
                      = render 'shareds/list_message'
                  li.dropdown
                    a href="#" class="dropdown-toggle dropdown-toggle-avatar" data-toggle="dropdown"
                      .thumb-avatar
                        = image_tag current_user.profile.avatar.url(:thumb)
                      span 
                        | <i class="fa fa-caret-down"></i>
                    ul class="dropdown-menu" role="menu"
                      li
                        = link_to '<i class="fa fa-home"></i> Beranda'.html_safe, userpage_dashboard_path
                      li
                        = link_to '<i class="fa fa-file-image-o"></i> Iklan Anda'.html_safe, userpage_products_path
                      li
                        = link_to '<i class="fa fa-heart-o"></i> Iklan Favorit'.html_safe, userpage_favorites_path
                      li
                        = link_to '<i class="fa fa-wrench"></i> Pengaturan'.html_safe, user_edit_url(current_user.type, current_user)
                      li
                        = link_to '<i class="fa fa-mail-reply"></i> Keluar'.html_safe, destroy_user_session_path, method: 'delete'
  = flash_messages

  - if params[:action] == 'home'
    = render 'shareds/carousel'
  - if params[:controller] == 'products' && params[:action] == 'index' || params[:action] == 'home'
    = render 'shareds/home/categories'
  - if params[:controller] == 'products' && params[:action] == 'index'
    section.section-breadcrumb.white.shadow
      .container
        .row
          .col-md-12
            .row
              .col-md-3.breadcrumb
                = render_breadcrumbs
              .col-md-9
                span.title-content-product
                  | Ditemukan <b>#{@product_all.size}</b> Iklan
              = render 'shareds/products/simple_search'

              