config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions',
      confirmations: "confirmations"
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }

  root 'publics#home'

  # get 'contact', to: 'publics#contact', as: 'contact'

  resources :products do
    collection do
      get :auction
      get :featureds, to: 'products#featured'
      get 'wishlist/:id', to: 'products#wishlist', as: 'wishlist'
      post :checkout_bid
    end
    member do
      match :upvote, path: 'like', via: [:get, :post, :put]
      get 'reviews', to: 'products#reviews'
      delete 'reviews/:rate_id', to: 'products#delete_reviews', as: 'delete_rate'
      post 'reviews', to: 'reviews#create'
    end
  end
  resources :favorites do
    collection do
      get :wishlist
    end
  end
  resources :subscribes
  resources :landing_pages
  resources :comments
  resources :reports, only: [:create]
  resources :inquiries do
    collection do
      post :create_instant_message
    end
  end
  resources :guest_books
  resources :users do
    member do
      match :upvote, path: 'like', via: [:get, :post, :put]
    end
  end
  resources :blogs do
    member do
      get :category
    end
    collection do 
      get :results
    end
  end
  resources :xhrs do
    collection do
      get :cities
      get :districts
      get :villages
      get :sub_categories
      get :brands
    end
  end

  namespace :backend do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :admins
    resources :members do
      collection do
        post :do_multiple_act
      end
    end
    resources :merchants do
      collection do
        post :do_multiple_act
      end
    end
    resources :categories do
      collection do
        post :do_multiple_act
      end
    end
    resources :products do
      collection do
        get :pending
        get :archive
        post :do_multiple_act
      end
      member do
        get :restore
      end
    end
    resources :regions do
      collection do
        post :do_multiple_act
      end
    end
    resources :reports do
      collection do
        post :do_multiple_act
      end
    end
    resources :comments do
      collection do
        post :do_multiple_act
      end
    end
    resources :landing_pages do
      collection do
        post :do_multiple_act
      end
    end
    resources :subscribes do
      collection do
        post :do_multiple_act
      end
    end
    resources :testimonials do
      collection do
        post :do_multiple_act
      end
    end
    resources :blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :category_blogs do
      collection do
        post :do_multiple_act
      end
    end
    resources :web_settings
  end

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members, only: [:edit, :update, :show]
    resources :merchants, only: [:edit, :update, :show]
    resources :products do
      collection do
        get :pending
        get :archive
      end
      member do
        get :restore
      end
    end
    resources :favorites
    resources :inquiries
  end
end

app/controllers/backend/admins_controller.rb
class Backend::AdminsController < Backend::ApplicationController
  defaults resource_class: Admin, collection_name: 'admins', instance_name: 'admin'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Admins"

  def index
    @collection = collection.latest.page(page).per(per_page)
  end
  
  def update
    update! do |format|
      if resource.errors.empty?
        format.html {redirect_to :back}
      else
        format.html {redirect_to :back, errors: resource.errors.full_messages}
      end
    end
  end
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < Backend::ResourcesController
  layout 'backend'

  before_filter :authenticate_admin!, :prepare_count
  protect_from_forgery with: :exception

  def authenticate_admin!
    unless current_user.present? && (current_user.admin?)
      redirect_to root_path, alert: "Can't Access this page"
    end
  end

  protected
    def prepare_count
      @members_size = Member.all.size
      @merchants_size = Merchant.all.size
      @products_size = Product.all.size
    end

    def per_page
      params[:per_page] ||= 20
    end

    def page
      params[:page] ||= 1
    end
end

app/controllers/backend/blogs_controller.rb
class Backend::BlogsController < Backend::ApplicationController
  defaults resource_class: Blog, collection_name: 'blogs', instance_name: 'blog'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Blog", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/categories_controller.rb
class Backend::CategoriesController < Backend::ApplicationController
  defaults resource_class: Category, collection_name: 'categories', instance_name: 'category'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Categories", :collection_path

  include MultipleAction

  def index
    @collection = collection.roots.alfa.page(page).per(per_page)
  end

  def edit
    @collection = resource.children.alfa
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/category_blogs_controller.rb
class Backend::CategoryBlogsController < Backend::ApplicationController
  defaults resource_class: CategoryBlog, collection_name: 'category_blogs', instance_name: 'category_blog'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Category Blog", :collection_path

  include MultipleAction
  
  def index
    @collection = collection.roots.alfa.page(page).per(per_page)
  end

  def edit
    @collection = resource.children.alfa
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::ApplicationController
  add_breadcrumb "Dashboard", :backend_dashboard_path

  def dashboard
    
  end
end

app/controllers/backend/landing_pages_controller.rb
class Backend::LandingPagesController < Backend::ApplicationController
  defaults resource_class: LandingPage, collection_name: 'landing_pages', instance_name: 'landing_page'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Landing Page", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/members_controller.rb
class Backend::MembersController < Backend::ApplicationController
  defaults resource_class: Member, collection_name: 'members', instance_name: 'member'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Members", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end
  
  def update
    update! do |format|
      if resource.errors.empty?
        format.html {redirect_to :back}
      else
        format.html {redirect_to :back, errors: resource.errors.full_messages}
      end
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/merchants_controller.rb
class Backend::MerchantsController < Backend::ApplicationController
  defaults resource_class: Merchant, collection_name: 'merchants', instance_name: 'merchant'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Merchants", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end
  
  def update
    update! do |format|
      if resource.errors.empty?
        format.html {redirect_to :back}
      else
        format.html {redirect_to :back, errors: resource.errors.full_messages}
      end
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/products_controller.rb
class Backend::ProductsController < Backend::ApplicationController
  defaults resource_class: Product, collection_name: 'products', instance_name: 'product'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Products", :collection_path

  include MultipleAction

  def index
    @collection = collection.verify
  end

  def pending
    @collection = collection.unverify
  end

  def archive
    @collection = collection.only_deleted
  end

  def create
    build_resource
    create! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
  end

  def update
    update! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end
  end

  def restore
    resource = collection.with_deleted.find params[:id]
    if resource.restore(recursive: true)
      redirect_to :back, notice: "Product code #{resource.code} successfully restore!"
    else
      redirect_to :back, alert: 'Error'
    end
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params).latest.page(page).per(per_page)
    end
end

app/controllers/backend/regions_controller.rb
class Backend::RegionsController < Backend::ApplicationController
  defaults resource_class: Region, collection_name: 'regions', instance_name: 'region'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Regions", :collection_path

  include MultipleAction
  
  def index
    @collection = collection.roots.alfa.page(page).per(per_page)
  end

  def create
    build_resource
    create! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        flash[:errors] = resource.errors.full_messages
        format.html {redirect_to :back}
      end
    end

  end


  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/reports_controller.rb
class Backend::ReportsController < Backend::ApplicationController
  defaults resource_class: Report, collection_name: 'reports', instance_name: 'report'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Reports", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/resources_controller.rb
class Backend::ResourcesController < InheritedResources::Base
  include Parameters

  def create
    create! do |success, failure|
      success.html { redirect_to collection_path }
      failure.html do
        logger.debug resource.errors.full_messages
        flash[:error] = resource.errors.full_messages
        redirect_to :back
      end
    end
  end

  def update
    update! do |success, failure|
      success.html { redirect_to collection_path }
    end
  end
end

app/controllers/backend/subscribes_controller.rb
class Backend::SubscribesController < Backend::ApplicationController
  defaults resource_class: Subscribe, collection_name: 'subscribes', instance_name: 'subscribe'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Subscribes", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  protected
    def collection
      @collection ||= end_of_association_chain.search_by(params)
    end
end

app/controllers/backend/testimonials_controller.rb
class Backend::TestimonialsController < Backend::ApplicationController
  defaults resource_class: Testimonial, collection_name: 'testimonials', instance_name: 'testimonial'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Testimonials", :collection_path

  include MultipleAction

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/backend/web_settings_controller.rb
class Backend::WebSettingsController < Backend::ApplicationController
  defaults resource_class: WebSetting, collection_name: 'web_settings', instance_name: 'web_setting'

  add_breadcrumb "Dashboard", :backend_dashboard_path
  add_breadcrumb "Web Settings", :collection_path

  def index
    @collection = collection.latest.page(page).per(per_page)
  end

  protected
    def collection
      @collection ||= end_of_association_chain
    end
end

app/controllers/products_controller.rb
class ProductsController < FrontendController
  add_breadcrumb "Home", :root_path
  add_breadcrumb "Iklan", :products_path

  before_action :prepare_simple_search, only: [:index]

  def index
    categories

    if params[:category].present?
      @category = Category.find_by(name: params[:category])
    end

    @product_all = collection.latest.search_by(params)
    @products = @product_all.page(page).per(per_page)
  end

  def show
    add_breadcrumb "#{resource.title}"

    resource
    @user = resource.user
    @user_products = @user.products.verify.latest.limit(5)
    @profile = @user.profile
    @address = @user.address
    @contact = @user.contact
    @merchant = @user.merchant_info
    impressionist(@product, 'message')

    @favorites_size = @product.favorites.size
    @comments_size = @product.comments.size
    @comments = @product.comments.latest.page(page).per(per_page)

    @product = Product.find params[:id]

    rating(@product.id)
  end

  def new
    add_breadcrumb "Produk Baru"

    @product = Product.new
  end

  def upvote
    @link = Product.find params[:id]
    @success = @link.upvote_by current_user
    if @success
      redirect_to :back, alert: "Anda sudah menyukai iklan ini!"
    else
      redirect_to :back, error: "Anda tidak berhasil menyukai iklan ini!"
    end
  end

  def delete_reviews
    rate = Rate.find(params[:rate_id])
    if rate.delete
      flash[:success] = 'Review anda berhasil di hapus!'
    else
      flash[:error] = rate.errors.full_message
    end
    redirect_to product_path(params[:id])
  end

  private
    def collection
      @products = Product.verify
    end

    def resource
      @product = Product.find params[:id]
    end

    def categories
      @categories = Category.roots.oldest
    end

    def prepare_simple_search
      @cities = Region.roots.alfa.pluck(:name)
    end

    def rating(product_id)
      @reviews = Rate.where(rateable_id: product_id).page(page).per(per_page)
    end
end

app/controllers/userpage/products_controller.rb
class Userpage::ProductsController < Userpage::ApplicationController
  defaults resource_class: Product, collection_name: 'products', instance_name: 'product'

  add_breadcrumb "Dashboard", :userpage_dashboard_path
  add_breadcrumb "Iklan Saya", :collection_path

  def index
    add_breadcrumb "Iklan Tayang"
    @products = current_user.products.latest.verify.search_by(params)
    @collection = @products.page(page).per(per_page)
  end

  def pending
    add_breadcrumb "Iklan Belum Tayang"
    @products = current_user.products.latest.unverify.search_by(params)
    @collection = @products.page(page).per(per_page)
  end

  def archive
    add_breadcrumb "Arsip"
    @products = current_user.products.latest.only_deleted.search_by(params)
    @collection = @products.page(page).per(per_page)
  end

  def new
    add_breadcrumb "Pasang Iklan"
    super
  end

  def edit
    add_breadcrumb "Ubah Iklan"
    super
  end

  def create
    build_resource
    resource.user_id = current_user.id
    create! do |format|
      if resource.errors.empty?
        UserMailer.send_request_product(resource).deliver
        format.html {redirect_to :back, notice: 'Iklan anda berhasil dibuat dan akan segera bisa dilihat setelah di verifikasi oleh Staf Admin Kami, Verifikasi Max 1 x 24 Jam! Terimakasih '}
      else
        format.html {redirect_to :back, error: resource.errors.full_messages}
      end
    end
  end

  def update
    update! do |format|
      if resource.errors.empty?
        format.html {redirect_to collection_path}
      else
        format.html {redirect_to :back, error: resource.errors.full_messages}
      end
    end
  end

  def destroy
    destroy! do |format|
      if resource.errors.empty?
        format.html {redirect_to :back}
      else
        format.html {redirect_to :back, error: resource.errors.full_messages}
      end
    end
  end

  def restore
    resource = collection.with_deleted.find params[:id]
    if resource.restore(recursive: true)
      redirect_to :back, notice: "Iklan #{resource.code} berhasil di kembalikan!"
    else
      redirect_to :back, alert: 'Error'
    end
  end
end

app/views/backend/products/_form.html.slim
.row
  .col-md-12
    .row
      - CategoryProduct.to_a.each do |c|
        .col-md-6
          .well
            center
              h2 #{c[1].titleize}
              p = f.radio_button :category, c[1]
      .col-md-6
        h6 User
        = f.select :user_id, User.pluck(:username, :id), {prompt: 'Select User'}, {class: 'form-control select2', required: true} 
      .col-md-6
        h6 Price
        = f.text_field :price, value: resource.basic_price, class: 'form-control', required: true, placeholder: 'ex. 10000000', data: {autonumeric: true}
      .col-md-4
        h6 Category
        = f.select :category_id, options_for_select(Category.roots.alfa.map{|c| [c.name, c.id]}, f.object.category_id), {prompt: 'Pilih Kategori'}, class: 'select2 form-control choice-category-select', 'data-node' => "#{resource.class.to_s.downcase}", required: true
      .col-md-4
        h6 Sub Category
        .sub-category-container
          - sub_categories = Category.find(resource.category_id).try(:children).alfa.map{|c| [c.name, c.id]} rescue []
          = f.select :sub_category_id, options_for_select(sub_categories, resource.sub_category_id), {prompt: 'Pilih Sub Kategori'}, class: 'select2 form-control choice-sub-category-select', 'data-node' => "#{resource.class.to_s.downcase}", required: true
      .col-md-4
        h6 Brand
        .brand-container
          - brands = Category.find(resource.sub_category_id).try(:children).alfa.map{|c| [c.name, c.id]} rescue []
          = f.select :brand_id, options_for_select(brands, resource.brand_id), {prompt: 'Pilih Merek'}, class: 'select2 form-control'
      .col-md-12
        h6 Title
        = f.text_field :title, class: 'form-control', required: true 
      .col-md-12
        h6 Description
        = f.cktext_area :description, class: 'form-control', required: true
      .col-md-6
        br
        .well
          center
            p Featured
            p = f.check_box :featured
      .col-md-6
        br
        .well
          center
            p Published
            p = f.check_box :status
.row
  .col-md-12
    h3 Gallery
    hr
    .setup-content
      ul.choice-gallery-form
        = f.fields_for :galleries do |g|
          = render 'gallery_fields', f: g
.break

.row
  .col-md-12
    = f.fields_for :address do |address|
      = render 'form_address', address: address
.break

app/views/backend/products/_form_address.html.slim
h3 Address Location
hr
.row
  .col-md-6
    h6 City
    = address.select :city, options_for_select(Region.roots.alfa.pluck(:name), resource.address.city), {prompt: 'Pilih Kota/Kabupaten'}, class: 'select2 form-control cities_select','data-node' => "#{resource.class.to_s.downcase}"
  .col-md-6
    h6 District
    - districts = address.object.district ? Region.find_by(name: address.object.city).try(:children).pluck(:name) || [] : Region.none rescue []
    .district-container
      = address.select :district, options_for_select(districts, resource.address.district), {prompt: 'Pilih Kecamatan'}, class: 'select2 form-control district_select', 'data-node' => "#{resource.class.to_s.downcase}"
  .col-md-6
    h6 Village
    - villages = address.object.village ? Region.find_by(name: address.object.district).try(:children).pluck(:name) || [] : Region.none rescue []
    .village-container
      = address.select :city, options_for_select(villages, resource.address.village), {prompt: 'Pilih Desa'}, class: 'select2 form-control'
  .col-md-6
    h6 Postcode
    = address.text_field :postcode, class: 'form-control'
  .col-md-12
    h6 Address
    = address.text_area :address, class: 'form-control'
  .col-md-6
    h6 Longitude
    = address.text_field :longitude, class: 'form-control'
  .col-md-6
    h6 Latitude
    = address.text_field :latitude, class: 'form-control'

app/views/backend/products/_gallery_fields.html.slim
li
	= image_tag f.object.file.url(:small), class: 'show-choice'
	= f.file_field :file, class: 'input-file'
	= f.hidden_field :position

app/views/backend/products/archive.html.slim
.col-md-12
	.row
	  = form_for :search, url: archive_backend_products_path, method: 'get' do 
	    .col-md-12
	      h6 Find Results <b> #{collection.size} </b>
	    .col-md-6
	      = text_field_tag :key, nil, value: params[:key], class: 'form-control', placeholder: 'keywords..' 
	    .col-md-5
	      = select_tag :category, options_for_select(Category.roots.alfa.pluck(:name), params[:category]), prompt: 'Choice Category', class: 'select2 form-control'
	    .col-md-1.padding0
	      button class="btn btn-info" type="submit" Search
	= form_for :multiple, url: "#{collection_path}/do_multiple_act", method: 'post' do
		.widget
			= render partial: 'backend/shareds/prepare_table', locals: {table_name: 'Products', button_name: 'Product', add_method: true}
			.widget-content
				.table-responsive
					table class="table table-striped table-bordered table-hover"
						thead
							tr
								th width="1%" #
								th Product Id
								th Image
								th Title
								th Price
								th Category
								th Sub Category
								th Status
								th Created At
								th Action
						tbody
							- @collection.each_with_index do |resource, index|
								tr
									td = check_box_tag "ids[]", resource.id
									td = resource.code
									td
										center
											= image_tag resource.galleries.with_deleted.first.file.url(:thumb), class: "thumb-ads"
									td
										= link_to resource.title, product_path(resource)
										= resource.featured?
										br
										small
											| from: #{link_to resource.user.merchant_info.title, user_path(resource.user)}
									td 
										= get_currency(resource.price) if resource.price.present?
									td = resource.try(:parent_category).try(:name)
									td = resource.try(:sub_category).try(:name)
									td
										= resource.active?
									td = resource.created_at.strftime("%b, %d, %Y") if resource.created_at.present?
									td
										= link_to '<i class="fa fa-undo"></i> restore'.html_safe, restore_backend_product_path(resource), class: 'btn btn-xs btn-success'
				.widget-foot
					.pull-right
						= paginate @collection
					.clearfix

app/views/backend/products/edit.html.slim
= render partial: 'backend/shareds/prepare_form',
            locals: { form_name: 'Products', action_name: 'Edit', form_method: 'put'}

app/views/backend/products/index.html.slim
.col-md-12
	= render 'backend/shareds/search_form_product'
	= form_for :multiple, url: "#{collection_path}/do_multiple_act", method: 'post' do
		.widget
			= render partial: 'backend/shareds/prepare_table', locals: {table_name: 'Products', button_name: 'Product', add_method: true}
			.widget-content
				.table-responsive
					table class="table table-striped table-bordered table-hover"
						thead
							tr
								th width="1%"
									.check_all_box 
										= check_box_tag :check_all
								th Product Id
								th Status
								th Image
								th Title
								th Price
								th Category
								th Sub Category
								th Status
								th Created At
								th Action
						tbody
							- @collection.each_with_index do |resource, index|
								tr
									td = check_box_tag "ids[]", resource.id
									td = resource.code
									td = resource.category.titleize if resource.category.present?
									td
										center
											= image_tag resource.galleries.first.file.url(:thumb), class: "thumb-ads"
									td
										= link_to resource.title, product_path(resource)
										= resource.featured?
										br
										small
											| from: #{link_to resource.user.merchant_info.title, user_path(resource.user)}
									td 
										= get_currency(resource.price) if resource.price.present?
									td = resource.try(:parent_category).try(:name)
									td = resource.try(:sub_category).try(:name)
									td
										= resource.active?
									td = resource.created_at.strftime("%b, %d, %Y") if resource.created_at.present?
									td
										= render partial: 'backend/shareds/prepare_action',
	                    locals: { resource: resource, confirmation: "Are you sure delete this #{resource.id}", no_show: false }
				.widget-foot
					.pull-right
						= paginate @collection
					.clearfix

app/views/backend/products/new.html.slim
= render partial: 'backend/shareds/prepare_form',
            locals: { form_name: 'Products', action_name: 'New', form_method: 'post'}

app/views/backend/products/pending.html.slim
.col-md-12
	.row
	  = form_for :search, url: pending_backend_products_path, method: 'get' do 
	    .col-md-12
	      h6 Find Results <b> #{collection.size} </b>
	    .col-md-6
	      = text_field_tag :key, nil, value: params[:key], class: 'form-control', placeholder: 'keywords..' 
	    .col-md-5
	      = select_tag :category, options_for_select(Category.roots.alfa.pluck(:name), params[:category]), prompt: 'Choice Category', class: 'select2 form-control'
	    .col-md-1.padding0
	      button class="btn btn-info" type="submit" Search
	= form_for :multiple, url: "#{collection_path}/do_multiple_act", method: 'post' do
		.widget
			= render partial: 'backend/shareds/prepare_table', locals: {table_name: 'Products', button_name: 'Product', add_method: true}
			.widget-content
				.table-responsive
					table class="table table-striped table-bordered table-hover"
						thead
							tr
								th width="1%"
									.check_all_box 
										= check_box_tag :check_all
								th Product Id
								th Image
								th Title
								th Price
								th Category
								th Sub Category
								th Status
								th Created At
								th Action
						tbody
							- @collection.each_with_index do |resource, index|
								tr
									td = check_box_tag "ids[]", resource.id
									td = resource.code
									td
										center
											= image_tag resource.galleries.first.file.url(:thumb), class: "thumb-ads"
									td
										= link_to resource.title, product_path(resource)
										= resource.featured?
										br
										small
											| from: #{link_to resource.user.merchant_info.title, user_path(resource.user)}
									td 
										= get_currency(resource.price) if resource.price.present?
									td = resource.try(:parent_category).try(:name)
									td = resource.try(:sub_category).try(:name)
									td
										= resource.active?
									td = resource.created_at.strftime("%b, %d, %Y") if resource.created_at.present?
									td
										= render partial: 'backend/shareds/prepare_action',
	                    locals: { resource: resource, confirmation: "Are you sure delete this #{resource.id}", no_show: false }
				.widget-foot
					.pull-right
						= paginate @collection
					.clearfix